### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by NicolasCharpentier** [LearnersGuild/rethinkdb-changefeed-reconnect#3]
Hi,

I am on a recent version of node.js and (so) using ecmascript 6. 

I encounter this error, maybe I don't feel the requirements ?

![image](https://cloud.githubusercontent.com/assets/9944995/20538199/708f3dc0-b0f0-11e6-8dce-75d97fd6598a.png)

Also, the example link on the readme is dead.

Thanks!

**Comment by jeffreywescott** [comment]
Not 100% sure, but I am guessing this is related to the fact that we use babel and some ES7-isms (like async / await). Can you point me to your code?

I'll fix the README, but the example is in the "example" folder of the repo.

**Comment by NicolasCharpentier** [comment]
Just a require-call will make it throw,  you are surely right, anyway thanks guess I dont have much solutions

**Comment by jeffreywescott** [comment]
@NicolasCharpentier I'm going to re-open this because I _do_ think it's an issue. Maybe someone will come up with a fix. I may try to address it myself when I get some time.

**Comment by jeffreywescott** [comment]
Hi, @NicolasCharpentier. This should have been fixed by #4. Would you try again and see if things work for you? If they do, please close the issue again.

Thanks!

**Comment by NicolasCharpentier** [comment]
Thank you!! 

So i downloaded 0.3.0 from git, I no longer encounter the precedent error, but still am having problem, "cursor.each is not a function" while i am just using console.log. Am I doing something wrong ?

Btw I use thinky

![image](https://cloud.githubusercontent.com/assets/9944995/20581454/3dd6b6ee-b1d9-11e6-9077-775bc6f0b2d7.png)

![image](https://cloud.githubusercontent.com/assets/9944995/20581459/4794bca8-b1d9-11e6-8123-5329bab94b95.png)

![image](https://cloud.githubusercontent.com/assets/9944995/20581464/4f6f143c-b1d9-11e6-9453-171fa6393fe3.png)

![image](https://cloud.githubusercontent.com/assets/9944995/20581469/5714c1aa-b1d9-11e6-9a52-70302f51d50d.png)


Usually i use the stream cursor like this, with an each too :

![image](https://cloud.githubusercontent.com/assets/9944995/20581538/ddf9e16e-b1d9-11e6-8f32-b266a9fbb61e.png)

**Comment by jeffreywescott** [comment]
Please have a look at the example.

Because we need to handle all of the errors that are encountered, you don't deal with the `cursor.each` yourself, but instead write an item handler. The example should make it clear.

**Comment by NicolasCharpentier** [comment]
Hi. Yes i tried your way, my 'cursor.each' part is the old way i used streams, posting this last screen was maybe a bad idea ; but anyway I have an item-handler which is the console.log you see, I dont get why this would not work.

**EDIT : Ok my bad, i was using a query not returning stream. All good, thank you**
