### ISSUE TITLE
How can a change feed be canceled?

### ISSUE THREAD

**Issue by paulrobello** [LearnersGuild/rethinkdb-changefeed-reconnect#9]
Normally you close the cursor to cancel the change feed, however you dont seem to expose the cursor or a way to cancel it.

**Comment by jeffreywescott** [comment]
Have you tried calling `.close()` on the cursor that would be returned from your `getFeed` function? 

I'm not sure I understand what you're asking. Do you have some code to share?

**Comment by paulrobello** [comment]
Thank you.  I totally over thought it. 
I will just save a ref to the cursor getFeed returns.
